### ISSUE TITLE
Show BlogPage description under BlogPage title in BlogIndexPage template 

### ISSUE THREAD

**Issue by Rascat** [bocian67/dezentrale_web#50]
Self explanatory
This could help getting an idea what the several blog article are actually about before having to click the link.

**Comment by elbenfreund** [comment]
Seems reasonable. Just make sure that you limit the intro length somewhere. Obvious options are:
- Limit the max_length of ``BlogPage.intro``
- Limit the length of the string rendered in the template.

**Comment by bocian67** [comment]
#50
I pushed a solution just as I thought, but why doesn't I shows up? @elbenfreund do you have a good solution?

**Comment by elbenfreund** [comment]
Please refer to the [docs](http://docs.wagtail.io/en/v1.11.1/topics/streamfield.html#template-rendering)
Also. I am still not convinced that there is a clear understanding *what* streamfields are and more importantly *what problem they try to address*. So far, your implementation gives the very strong indication that you really really should not use it in your current use case. 

The main point to understand is: template authors can make only very few assumptions about the internal structure of of stream field content. In our case: it simply does not make *any* sense (as far as I can see). 
In general content within a stream field is (re-)orderable. that means a template can not know in which order content is provided. thats the whole point. **if** you want to place specific content at a specific place of the page (as i suspect you want to do) then a streamfield is most likely the wrong tool to use.

**Comment by elbenfreund** [comment]
Also content can consist of multiple blocks. So the general idea (if you insist on using stream fields) is to get the first child element of ``content``, trucate its content, and render it.

**Comment by bocian67** [comment]
I now had improved the style for the streamfield usage, your explaination helped a lot, thank you. Now I have my original problem, that I cannot display the teaser or the author (nevermind what, I just can see the title) in the blog_index_page for each blog_page. The goal of this issue should be that the Teaser is readable in the indexpage, but its not showing up @elbenfreund.
